CREATE TABLE PRODUCT
( PROD_ID VARCHAR2(10) NOT NULL
 ,PROD_NM VARCHAR2(100) NOT NULL
 ,REG_DT DATE NOT NULL
 ,REGR_NO NUMBER(10)
 ,CONSTRAINT PRODUCT_PK PRIMARY KEY (PROD_ID) );
 
 SELECT * FROM PRODUCT1;
 
 CREATE TABLE PRODUCT3
( PROD_ID VARCHAR2(10) NOT NULL
 ,PROD_NM VARCHAR2(100) NOT NULL
 ,REG_DT DATE NOT NULL
 ,REGR_NO NUMBER(10)
 ,ADD CONSTRAINT PRIMARY KEY (PROD_ID) );
 
 CREATE TABLE PRODUCT2
( PROD_ID VARCHAR2(10) NOT NULL
 ,PROD_NM VARCHAR2(100) NOT NULL
 ,REG_DT DATE NOT NULL
 ,REGR_NO NUMBER(10) NULL );
 ATLER TABLE PRODUCT1 ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (PROD_ID);
 
 ,CONSTRAINT PRODUCT_PK PRIMARY KEY (PROD_ID) );
 

CREATE TABLE T
(C INTEGER PRIMARY KEY,
 D INTEGER);
 
CREATE TABLE S
(B INTEGER PRIMARY KEY,
 C INTEGER REFERENCES T(C) ON DELETE CASCADE);
 
CREATE TABLE R
(A INTEGER PRIMARY KEY,
 B INTEGER REFERENCES S(B) ON DELETE SET NULL);
 
SELECT * FROM T;
SELECT * FROM S;
SELECT * FROM R;

INSERT INTO T
    VALUES (1,1);
INSERT INTO T
    VALUES (2,1); 
    
INSERT INTO S
    VALUES (1,1);
INSERT INTO S
    VALUES (2,1); 

INSERT INTO R
    VALUES (1,1);
INSERT INTO R
    VALUES (2,2); 

DELETE FROM T;

#테이블이름변경
RENAME STADIUM TO STADIUM_JSC;


CREATE TABLE TAB1
( COL1 VARCHAR2(10) NOT NULL
 ,COL2 VARCHAR2(10) );